"""AUTO-GENERATED by tools/generate_accessors.py — do not edit.

Static ``@property`` accessors for the Raumdaten dataset (V221).
Regenerate with: pixi run -e dev python tools/generate_accessors.py
"""

from __future__ import annotations

from typing import Any  # noqa: F401


class RoomUseProperties:
    """Generated ``@property`` accessors for the 45 standard room uses."""

    @property
    def residential_mfh(self) -> Any:
        """1.01 Wohnen MFH."""
        return self._room_use_by_slug("residential_mfh")

    @property
    def residential_sfh(self) -> Any:
        """1.02 Wohnen EFH."""
        return self._room_use_by_slug("residential_sfh")

    @property
    def hotel_room(self) -> Any:
        """2.01 Hotelzimmer."""
        return self._room_use_by_slug("hotel_room")

    @property
    def lobby_reception(self) -> Any:
        """2.02 Empfang, Lobby."""
        return self._room_use_by_slug("lobby_reception")

    @property
    def group_office(self) -> Any:
        """3.01 Einzel-, Gruppenbüro."""
        return self._room_use_by_slug("group_office")

    @property
    def open_plan_office(self) -> Any:
        """3.02 Grossraumbüro."""
        return self._room_use_by_slug("open_plan_office")

    @property
    def meeting_room(self) -> Any:
        """3.03 Sitzungszimmer."""
        return self._room_use_by_slug("meeting_room")

    @property
    def reception_hall(self) -> Any:
        """3.04 Schalterhalle, Empfang."""
        return self._room_use_by_slug("reception_hall")

    @property
    def classroom(self) -> Any:
        """4.01 Schulzimmer."""
        return self._room_use_by_slug("classroom")

    @property
    def teacher_room(self) -> Any:
        """4.02 Lehrerzimmer."""
        return self._room_use_by_slug("teacher_room")

    @property
    def library(self) -> Any:
        """4.03 Bibliothek."""
        return self._room_use_by_slug("library")

    @property
    def lecture_hall(self) -> Any:
        """4.04 Hörsaal."""
        return self._room_use_by_slug("lecture_hall")

    @property
    def specialist_classroom(self) -> Any:
        """4.05 Schulfachraum (Spezialraum)."""
        return self._room_use_by_slug("specialist_classroom")

    @property
    def grocery_shop(self) -> Any:
        """5.01 Lebensmittelverkauf."""
        return self._room_use_by_slug("grocery_shop")

    @property
    def specialty_shop(self) -> Any:
        """5.02 Fachgeschäft."""
        return self._room_use_by_slug("specialty_shop")

    @property
    def furniture_store(self) -> Any:
        """5.03 Verkauf Möbel, Bau, Garten."""
        return self._room_use_by_slug("furniture_store")

    @property
    def restaurant(self) -> Any:
        """6.01 Restaurant."""
        return self._room_use_by_slug("restaurant")

    @property
    def cafeteria(self) -> Any:
        """6.02 Selbstbedienungsrestaurant."""
        return self._room_use_by_slug("cafeteria")

    @property
    def restaurant_kitchen(self) -> Any:
        """6.03 Küche zu Restaurant."""
        return self._room_use_by_slug("restaurant_kitchen")

    @property
    def cafeteria_kitchen(self) -> Any:
        """6.04 Küche zu Selbstbedienungsrest.."""
        return self._room_use_by_slug("cafeteria_kitchen")

    @property
    def auditorium(self) -> Any:
        """7.01 Vorstellungsraum."""
        return self._room_use_by_slug("auditorium")

    @property
    def multi_purpose_hall(self) -> Any:
        """7.02 Mehrzweckhalle."""
        return self._room_use_by_slug("multi_purpose_hall")

    @property
    def exhibition_hall(self) -> Any:
        """7.03 Ausstellungshalle."""
        return self._room_use_by_slug("exhibition_hall")

    @property
    def patient_room(self) -> Any:
        """8.01 Bettenzimmer."""
        return self._room_use_by_slug("patient_room")

    @property
    def ward_room(self) -> Any:
        """8.02 Stationszimmer."""
        return self._room_use_by_slug("ward_room")

    @property
    def treatment_room(self) -> Any:
        """8.03 Behandlungsraum."""
        return self._room_use_by_slug("treatment_room")

    @property
    def production_heavy(self) -> Any:
        """9.01 Produktion (grobe Arbeit)."""
        return self._room_use_by_slug("production_heavy")

    @property
    def production_fine(self) -> Any:
        """9.02 Produktion (feine Arbeit)."""
        return self._room_use_by_slug("production_fine")

    @property
    def laboratory(self) -> Any:
        """9.03 Laborraum."""
        return self._room_use_by_slug("laboratory")

    @property
    def storage_hall(self) -> Any:
        """10.01 Lagerhalle."""
        return self._room_use_by_slug("storage_hall")

    @property
    def gymnasium(self) -> Any:
        """11.01 Turnhalle."""
        return self._room_use_by_slug("gymnasium")

    @property
    def fitness_room(self) -> Any:
        """11.02 Fitnessraum."""
        return self._room_use_by_slug("fitness_room")

    @property
    def swimming_hall(self) -> Any:
        """11.03 Schwimmhalle."""
        return self._room_use_by_slug("swimming_hall")

    @property
    def circulation_area(self) -> Any:
        """12.01 Verkehrsfläche."""
        return self._room_use_by_slug("circulation_area")

    @property
    def circulation_24h(self) -> Any:
        """12.02 Verkehrsfläche 24 h."""
        return self._room_use_by_slug("circulation_24h")

    @property
    def staircase(self) -> Any:
        """12.03 Treppenhaus."""
        return self._room_use_by_slug("staircase")

    @property
    def utility_room(self) -> Any:
        """12.04 Nebenraum."""
        return self._room_use_by_slug("utility_room")

    @property
    def kitchenette(self) -> Any:
        """12.05 Küche, Teeküche."""
        return self._room_use_by_slug("kitchenette")

    @property
    def wc_bath_shower(self) -> Any:
        """12.06 WC, Bad, Dusche."""
        return self._room_use_by_slug("wc_bath_shower")

    @property
    def wc(self) -> Any:
        """12.07 WC."""
        return self._room_use_by_slug("wc")

    @property
    def locker_shower(self) -> Any:
        """12.08 Garderobe, Dusche."""
        return self._room_use_by_slug("locker_shower")

    @property
    def parking_garage(self) -> Any:
        """12.09 Parkhaus."""
        return self._room_use_by_slug("parking_garage")

    @property
    def laundry_room(self) -> Any:
        """12.10 Wasch- und Trockenraum."""
        return self._room_use_by_slug("laundry_room")

    @property
    def cold_room(self) -> Any:
        """12.11 Kühlraum."""
        return self._room_use_by_slug("cold_room")

    @property
    def server_room(self) -> Any:
        """12.12 Serverraum."""
        return self._room_use_by_slug("server_room")



class ParameterProperties:
    """Generated ``@property`` accessors for the parameter catalog."""

    @property
    def qo(self) -> Any:
        """Norm Aussentemperatur [qo]."""
        return self._parameter_by_slug("qo")

    @property
    def norm_lufttemperatur_kuehlerauslegung(self) -> Any:
        """Norm Lufttemperatur Kühlerauslegung [norm-lufttemperatur-k-hlerauslegung]."""
        return self._parameter_by_slug("norm_lufttemperatur_kuehlerauslegung")

    @property
    def norm_feuchtkugeltemperatur_kuehlerauslegung(self) -> Any:
        """Norm Feuchtkugeltemperatur Kühlerauslegung [norm-feuchtkugeltemperatur-k-hlerauslegung]."""
        return self._parameter_by_slug("norm_feuchtkugeltemperatur_kuehlerauslegung")

    @property
    def gebaeudekategorie_nach_sia_380_1(self) -> Any:
        """Gebäudekategorie nach SIA 380/1 [geb-udekategorie-nach-sia-380-1]."""
        return self._parameter_by_slug("gebaeudekategorie_nach_sia_380_1")

    @property
    def raumabmessungen(self) -> Any:
        """Raumabmessungen [1.1.1.1]."""
        return self._parameter_by_slug("raumabmessungen")

    @property
    def lR(self) -> Any:
        """Raumlänge [lR]."""
        return self._parameter_by_slug("lR")

    @property
    def dR(self) -> Any:
        """Raumtiefe [dR]."""
        return self._parameter_by_slug("dR")

    @property
    def hR(self) -> Any:
        """Raumhöhe [hR]."""
        return self._parameter_by_slug("hR")

    @property
    def ANGF(self) -> Any:
        """Nettogeschossfläche [ANGF]."""
        return self._parameter_by_slug("ANGF")

    @property
    def thermal_envelope_area(self) -> Any:
        """Thermische Gebäudehüllfläche [1.1.1.2]."""
        return self._parameter_by_slug("thermal_envelope_area")

    @property
    def umrechnungsfaktor_brutto_zu_nettofassadenflaeche(self) -> Any:
        """Umrechnungsfaktor  Brutto- zu Nettofassadenfläche [umrechnungsfaktor-brutto-zu-nettofassadenfl-che]."""
        return self._parameter_by_slug("umrechnungsfaktor_brutto_zu_nettofassadenflaeche")

    @property
    def row_16(self) -> Any:
        """row-16 [row-16]."""
        return self._parameter_by_slug("row_16")

    @property
    def bauphysikalische_eigenschaften(self) -> Any:
        """Bauphysikalische Eigenschaften [bauphysikalische-eigenschaften]."""
        return self._parameter_by_slug("bauphysikalische_eigenschaften")

    @property
    def Uop(self) -> Any:
        """U-Wert opake Bauteile [Uop]."""
        return self._parameter_by_slug("Uop")

    @property
    def Uw(self) -> Any:
        """U-Wert Fenster [Uw]."""
        return self._parameter_by_slug("Uw")

    @property
    def FF(self) -> Any:
        """Abminderungsfaktor für Fensterrahmen [1.1.1.4]."""
        return self._parameter_by_slug("FF")

    @property
    def waermebrueckenzuschlag_auf_gesamt_u_wert_fassade(self) -> Any:
        """Wärmebrückenzuschlag auf Gesamt-U-Wert Fassade [w-rmebr-ckenzuschlag-auf-gesamt-u-wert-fassade]."""
        return self._parameter_by_slug("waermebrueckenzuschlag_auf_gesamt_u_wert_fassade")

    @property
    def fg(self) -> Any:
        """Glasanteil [1.1.1.3]."""
        return self._parameter_by_slug("fg")

    @property
    def Ag(self) -> Any:
        """Glasfläche [Ag]."""
        return self._parameter_by_slug("Ag")

    @property
    def Aw(self) -> Any:
        """Fensterfläche [Aw]."""
        return self._parameter_by_slug("Aw")

    @property
    def Aop(self) -> Any:
        """Opake Gebäudehüllfläche [Aop]."""
        return self._parameter_by_slug("Aop")

    @property
    def g(self) -> Any:
        """Gesamtenergiedurchlassgrad Verglasung [g]."""
        return self._parameter_by_slug("g")

    @property
    def gtot(self) -> Any:
        """Gesamtenergiedurchlassgrad Verglasung und Sonnenschutz [gtot]."""
        return self._parameter_by_slug("gtot")

    @property
    def Cm(self) -> Any:
        """Wärmespeicherfähigkeit des Raumes [1.1.1.11]."""
        return self._parameter_by_slug("Cm")

    @property
    def row_29(self) -> Any:
        """row-29 [row-29]."""
        return self._parameter_by_slug("row_29")

    @property
    def raumklima(self) -> Any:
        """Raumklima [raumklima]."""
        return self._parameter_by_slug("raumklima")

    @property
    def qi_des_C(self) -> Any:
        """Raumtemperatur-Auslegungswert [1.1.1.12.C]."""
        return self._parameter_by_slug("qi_des_C")

    @property
    def qi_des_H(self) -> Any:
        """Raumtemperatur-Auslegungswert (Auslegung Heizung) [qi,des.H]."""
        return self._parameter_by_slug("qi_des_H")

    @property
    def qi_ave_C(self) -> Any:
        """Mittlere Raumtemperatur [1.1.1.13.C]."""
        return self._parameter_by_slug("qi_ave_C")

    @property
    def qi_ave_H(self) -> Any:
        """Mittlere Raumtemperatur (Jährlicher Heizwärmebedarf) [qi,ave.H]."""
        return self._parameter_by_slug("qi_ave_H")

    @property
    def ji_des_C(self) -> Any:
        """Relative Raumluftfeuchte [1.1.1.14.C]."""
        return self._parameter_by_slug("ji_des_C")

    @property
    def ji_des_H(self) -> Any:
        """Relative Raumluftfeuchte (Auslegung Befeuchtung) [ji,des.H]."""
        return self._parameter_by_slug("ji_des_H")

    @property
    def va_des_C(self) -> Any:
        """Mittlere Luftgeschwindigkeit [1.1.1.15.C]."""
        return self._parameter_by_slug("va_des_C")

    @property
    def va_des_H(self) -> Any:
        """Mittlere Luftgeschwindigkeit (Auslegung Heizung) [va,des.H]."""
        return self._parameter_by_slug("va_des_H")

    @property
    def schallschutz(self) -> Any:
        """Schallschutz [schallschutz]."""
        return self._parameter_by_slug("schallschutz")

    @property
    def laermempfindlichkeit(self) -> Any:
        """Lärmempfindlichkeit [1.1.1.16]."""
        return self._parameter_by_slug("laermempfindlichkeit")

    @property
    def LH(self) -> Any:
        """Anforderungswert an Dauergeräusche gebäudetech. Anlagen [1.1.1.17]."""
        return self._parameter_by_slug("LH")

    @property
    def T(self) -> Any:
        """Nachhallzeit [T]."""
        return self._parameter_by_slug("T")

    @property
    def row_43(self) -> Any:
        """row-43 [row-43]."""
        return self._parameter_by_slug("row_43")

    @property
    def row_44(self) -> Any:
        """row-44 [row-44]."""
        return self._parameter_by_slug("row_44")

    @property
    def row_45(self) -> Any:
        """row-45 [row-45]."""
        return self._parameter_by_slug("row_45")

    @property
    def Jahresprofil(self) -> Any:
        """Personenprofil [1.1.2.1]."""
        return self._parameter_by_slug("Jahresprofil")

    @property
    def row_47(self) -> Any:
        """row-47 [row-47]."""
        return self._parameter_by_slug("row_47")

    @property
    def row_48(self) -> Any:
        """row-48 [row-48]."""
        return self._parameter_by_slug("row_48")

    @property
    def row_49(self) -> Any:
        """row-49 [row-49]."""
        return self._parameter_by_slug("row_49")

    @property
    def row_50(self) -> Any:
        """row-50 [row-50]."""
        return self._parameter_by_slug("row_50")

    @property
    def row_51(self) -> Any:
        """row-51 [row-51]."""
        return self._parameter_by_slug("row_51")

    @property
    def tP_d_max(self) -> Any:
        """Nutzungsstunden pro Tag [1.1.2.2]."""
        return self._parameter_by_slug("tP_d_max")

    @property
    def tP_d(self) -> Any:
        """Volllaststunden pro Tag [1.1.2.3]."""
        return self._parameter_by_slug("tP_d")

    @property
    def dPr_w(self) -> Any:
        """Ruhetage pro Woche [1.1.2.4]."""
        return self._parameter_by_slug("dPr_w")

    @property
    def dP(self) -> Any:
        """Nutzungstage pro Jahr [1.1.2.5]."""
        return self._parameter_by_slug("dP")

    @property
    def fP(self) -> Any:
        """Jahresgleichzeitigkeit [1.1.2.7]."""
        return self._parameter_by_slug("fP")

    @property
    def full_load_hours_year(self) -> Any:
        """Volllaststunden pro Jahr [1.1.2.8]."""
        return self._parameter_by_slug("full_load_hours_year")

    @property
    def personnel_area(self) -> Any:
        """Personenfläche [1.1.2.9]."""
        return self._parameter_by_slug("personnel_area")

    @property
    def activity_level(self) -> Any:
        """Aktivitätsgrad [1.1.2.10]."""
        return self._parameter_by_slug("activity_level")

    @property
    def lcl_C(self) -> Any:
        """Wärmedämmwert der Bekleidung [1.1.2.11.C]."""
        return self._parameter_by_slug("lcl_C")

    @property
    def lcl_H(self) -> Any:
        """Wärmedämmwert der Bekleidung (Auslegung Heizung) [lcl.H]."""
        return self._parameter_by_slug("lcl_H")

    @property
    def FP_C(self) -> Any:
        """Sensible Wärmeeintragsleistung Personen [1.1.2.13.C]."""
        return self._parameter_by_slug("FP_C")

    @property
    def FP_H(self) -> Any:
        """Sensible Wärmeeintragsleistung Personen (Auslegung Heizung) [FP.H]."""
        return self._parameter_by_slug("FP_H")

    @property
    def QiP_d(self) -> Any:
        """Interne Wärmeeinträge Personen pro Tag [QiP,d]."""
        return self._parameter_by_slug("QiP_d")

    @property
    def QiP_a(self) -> Any:
        """Interne Wärmeeinträge Personen pro Jahr [QiP,a]."""
        return self._parameter_by_slug("QiP_a")

    @property
    def gP_C(self) -> Any:
        """Feuchteproduktion Personen [1.1.2.14.C]."""
        return self._parameter_by_slug("gP_C")

    @property
    def gP_H(self) -> Any:
        """Feuchteproduktion Personen (Auslegung Befeuchtung) [gP.H]."""
        return self._parameter_by_slug("gP_H")

    @property
    def ga(self) -> Any:
        """Feuchtequellen (ohne Personen) [1.1.2.15]."""
        return self._parameter_by_slug("ga")

    @property
    def row_69(self) -> Any:
        """row-69 [row-69]."""
        return self._parameter_by_slug("row_69")

    @property
    def lastprofil(self) -> Any:
        """Lastprofil [1.1.3.1]."""
        return self._parameter_by_slug("lastprofil")

    @property
    def row_71(self) -> Any:
        """row-71 [row-71]."""
        return self._parameter_by_slug("row_71")

    @property
    def row_72(self) -> Any:
        """row-72 [row-72]."""
        return self._parameter_by_slug("row_72")

    @property
    def row_73(self) -> Any:
        """row-73 [row-73]."""
        return self._parameter_by_slug("row_73")

    @property
    def row_74(self) -> Any:
        """row-74 [row-74]."""
        return self._parameter_by_slug("row_74")

    @property
    def row_75(self) -> Any:
        """row-75 [row-75]."""
        return self._parameter_by_slug("row_75")

    @property
    def tA_d(self) -> Any:
        """Volllaststunden pro Tag [1.1.2.3-2]."""
        return self._parameter_by_slug("tA_d")

    @property
    def equipment_power(self) -> Any:
        """Elektrische Leistung der Geräte [1.1.3.3]."""
        return self._parameter_by_slug("equipment_power")

    @property
    def process_power(self) -> Any:
        """Elektrische Leistung der Prozessanlagen [1.1.3.4]."""
        return self._parameter_by_slug("process_power")

    @property
    def off_hours_power(self) -> Any:
        """Leistung ausserhalb der Nutzungszeit [1.1.3.5]."""
        return self._parameter_by_slug("off_hours_power")

    @property
    def equipment_heat_gain(self) -> Any:
        """Wärmeeintragsleistung der Geräte [1.1.3.6]."""
        return self._parameter_by_slug("equipment_heat_gain")

    @property
    def QiA(self) -> Any:
        """Interne Wärmeeinträge der Geräte pro Tag [QiA]."""
        return self._parameter_by_slug("QiA")

    @property
    def tA_Ps(self) -> Any:
        """Jährliche Volllaststunden der Geräte und Prozessanlagen [1.1.3.7]."""
        return self._parameter_by_slug("tA_Ps")

    @property
    def QiA_a(self) -> Any:
        """Interne Wärmeeinträge der Geräte pro Jahr [QiA,a]."""
        return self._parameter_by_slug("QiA_a")

    @property
    def EA(self) -> Any:
        """Jährlicher Elektrizitätsbedarf der Geräte [1.1.3.8]."""
        return self._parameter_by_slug("EA")

    @property
    def EPs(self) -> Any:
        """Jährlicher Elektrizitätsbedarf der Prozessanlagen [1.1.3.9]."""
        return self._parameter_by_slug("EPs")

    @property
    def row_86(self) -> Any:
        """row-86 [row-86]."""
        return self._parameter_by_slug("row_86")

    @property
    def illuminance(self) -> Any:
        """Beleuchtungsstärke [1.1.4.1]."""
        return self._parameter_by_slug("illuminance")

    @property
    def reference_illuminance(self) -> Any:
        """Referenzbeleuchtungsstärke [1.1.4.2]."""
        return self._parameter_by_slug("reference_illuminance")

    @property
    def work_plane_height(self) -> Any:
        """Bewertungsebene [1.1.4.4]."""
        return self._parameter_by_slug("work_plane_height")

    @property
    def kR(self) -> Any:
        """Raumindex [1.1.4.5]."""
        return self._parameter_by_slug("kR")

    @property
    def MF(self) -> Any:
        """Wartungswert Beleuchtung [MF]."""
        return self._parameter_by_slug("MF")

    @property
    def lamp_efficacy(self) -> Any:
        """Leuchten-Lichtausbeute [1.1.4.6]."""
        return self._parameter_by_slug("lamp_efficacy")

    @property
    def hR(self) -> Any:
        """Raumwirkungsgrad [1.1.4.7]."""
        return self._parameter_by_slug("hR")

    @property
    def volllaststunden_pro_tag_fuer_eine_nutungszeit_von_11_h(self) -> Any:
        """Volllaststunden pro Tag für eine Nutungszeit von 11 h [volllaststunden-pro-tag-f-r-eine-nutungszeit-von-11-h]."""
        return self._parameter_by_slug("volllaststunden_pro_tag_fuer_eine_nutungszeit_von_11_h")

    @property
    def zg(self) -> Any:
        """Glasflächenzahl [1.1.4.3]."""
        return self._parameter_by_slug("zg")

    @property
    def zg0(self) -> Any:
        """Glasflächenzahl oberhalb welcher keine weitere Reduktion der Volllaststunden eintritt [zg0]."""
        return self._parameter_by_slug("zg0")

    @property
    def kc(self) -> Any:
        """Korrekturfaktor Beleuchtungssteuerung nach Tageslicht [kc]."""
        return self._parameter_by_slug("kc")

    @property
    def kRe(self) -> Any:
        """Korrekturfaktor Reflexionsgrad [kRe]."""
        return self._parameter_by_slug("kRe")

    @property
    def lichttransmissionsgrad(self) -> Any:
        """Lichttransmissionsgrad [1.1.1.8]."""
        return self._parameter_by_slug("lichttransmissionsgrad")

    @property
    def kT(self) -> Any:
        """Korrekturfaktor Transmissionsgrad [kT]."""
        return self._parameter_by_slug("kT")

    @property
    def hSt(self) -> Any:
        """Höhe Fenstersturz [hSt]."""
        return self._parameter_by_slug("hSt")

    @property
    def kli(self) -> Any:
        """Korrekturfaktor Fenstersturz [kli]."""
        return self._parameter_by_slug("kli")

    @property
    def aB(self) -> Any:
        """Balkontiefe [aB]."""
        return self._parameter_by_slug("aB")

    @property
    def kB(self) -> Any:
        """Korrekturfaktor Balkon [kB]."""
        return self._parameter_by_slug("kB")

    @property
    def ksp1(self) -> Any:
        """Korrekturfaktor Art des Sonnenschutzes [ksp1]."""
        return self._parameter_by_slug("ksp1")

    @property
    def ksp2(self) -> Any:
        """Korrekturfaktor Beleuchtungssteuerung für die Sonnenschutzsteuerung [ksp2]."""
        return self._parameter_by_slug("ksp2")

    @property
    def ksur(self) -> Any:
        """Korrekturfaktor Horrizontverschattung [ksur]."""
        return self._parameter_by_slug("ksur")

    @property
    def tLi_min(self) -> Any:
        """Minimale Volllaststundenzahl [tLi,min]."""
        return self._parameter_by_slug("tLi_min")

    @property
    def tL_11(self) -> Any:
        """Volllaststunden pro 11h Tag [tL,11]."""
        return self._parameter_by_slug("tL_11")

    @property
    def tLi_min_su(self) -> Any:
        """tLi,min,Sommer [tLi,min,su]."""
        return self._parameter_by_slug("tLi_min_su")

    @property
    def tL_11_su(self) -> Any:
        """Vollaststunden pro 11h Sommertag [tL,11,su]."""
        return self._parameter_by_slug("tL_11_su")

    @property
    def row_112(self) -> Any:
        """row-112 [row-112]."""
        return self._parameter_by_slug("row_112")

    @property
    def volllaststunden_fuer_allgemeine_nutzungszeiten(self) -> Any:
        """Volllaststunden für allgemeine Nutzungszeiten [volllaststunden-f-r-allgemeine-nutzungszeiten]."""
        return self._parameter_by_slug("volllaststunden_fuer_allgemeine_nutzungszeiten")

    @property
    def tud(self) -> Any:
        """Nutzungsstunden pro Tag [1.1.2.2-2]."""
        return self._parameter_by_slug("tud")

    @property
    def tun(self) -> Any:
        """Nutzungsstunden pro Nacht [tun]."""
        return self._parameter_by_slug("tun")

    @property
    def kPr(self) -> Any:
        """Präsenzmelder [kPr]."""
        return self._parameter_by_slug("kPr")

    @property
    def lighting_control_factor(self) -> Any:
        """Korrekturfaktor für Präsenzregelung [1.1.4.9]."""
        return self._parameter_by_slug("lighting_control_factor")

    @property
    def ksi(self) -> Any:
        """Korrekturfaktor Gleichzeitigkeit [ksi]."""
        return self._parameter_by_slug("ksi")

    @property
    def tL_d(self) -> Any:
        """Volllaststunden pro Tag mit Präsenzmelder [tL,d]."""
        return self._parameter_by_slug("tL_d")

    @property
    def tL_su(self) -> Any:
        """Volllaststunden Sommertag mit Präsenzmelder [tL,su]."""
        return self._parameter_by_slug("tL_su")

    @property
    def pL(self) -> Any:
        """Elektrische Leistung der Beleuchtung [1.1.4.10]."""
        return self._parameter_by_slug("pL")

    @property
    def FL(self) -> Any:
        """Wärmeeintragsleistung der Beleuchtung [1.1.4.11]."""
        return self._parameter_by_slug("FL")

    @property
    def QiL(self) -> Any:
        """Interne Wärmeeinträge der Beleuchtung pro Tag [QiL]."""
        return self._parameter_by_slug("QiL")

    @property
    def lighting_full_load_hours(self) -> Any:
        """Jährliche Volllaststunden der Beleuchtung [1.1.4.12]."""
        return self._parameter_by_slug("lighting_full_load_hours")

    @property
    def lighting_electricity(self) -> Any:
        """Jährlicher Elektrizitätsbedarf Beleuchtung [1.1.4.13]."""
        return self._parameter_by_slug("lighting_electricity")

    @property
    def row_126(self) -> Any:
        """row-126 [row-126]."""
        return self._parameter_by_slug("row_126")

    @property
    def wohnen_mfh(self) -> Any:
        """Wohnen MFH [1.1]."""
        return self._parameter_by_slug("wohnen_mfh")

    @property
    def row_128(self) -> Any:
        """row-128 [row-128]."""
        return self._parameter_by_slug("row_128")

    @property
    def row_129(self) -> Any:
        """Symbol [row-129]."""
        return self._parameter_by_slug("row_129")

    @property
    def fresh_air_per_person(self) -> Any:
        """Aussenluft-Volumenstrom pro Person [1.1.5.1]."""
        return self._parameter_by_slug("fresh_air_per_person")

    @property
    def mechanische_lueftung(self) -> Any:
        """mechanische Lüftung [mechanische-l-ftung]."""
        return self._parameter_by_slug("mechanische_lueftung")

    @property
    def tbV(self) -> Any:
        """Jährliche Betriebsstunden (Vol.Strom) [tbV]."""
        return self._parameter_by_slug("tbV")

    @property
    def hygienic_airflow(self) -> Any:
        """Hygienebedingter Aussenluft-Volumenstrom [1.1.5.2]."""
        return self._parameter_by_slug("hygienic_airflow")

    @property
    def process_airflow(self) -> Any:
        """Prozessbedingter Aussenluft-Volumenstrom [1.1.5.3]."""
        return self._parameter_by_slug("process_airflow")

    @property
    def infiltration_airflow(self) -> Any:
        """Aussenluft-Volumenstrom durch Infiltration [1.1.5.4]."""
        return self._parameter_by_slug("infiltration_airflow")

    @property
    def air_quality_class(self) -> Any:
        """Steuerung und Regelung des Luftvolumenstroms (einstufig, zweistufig, stufenlos) [1.1.5.5]."""
        return self._parameter_by_slug("air_quality_class")

    @property
    def steuerung_und_regelung_des_luftvolumenstroms_einstufig_zweistufig_stufenlos(self) -> Any:
        """Steuerung und Regelung des Luftvolumenstroms (einstufig, zweistufig, stufenlos) [1.1.5.5-2]."""
        return self._parameter_by_slug("steuerung_und_regelung_des_luftvolumenstroms_einstufig_zweistufig_stufenlos")

    @property
    def anlagentyp(self) -> Any:
        """Anlagentyp [anlagentyp]."""
        return self._parameter_by_slug("anlagentyp")

    @property
    def heat_recovery_temp_eff(self) -> Any:
        """Temperatur-Änderungsgrad der Wärmerückgewinnung [1.1.5.6]."""
        return self._parameter_by_slug("heat_recovery_temp_eff")

    @property
    def heat_recovery_annual_eff(self) -> Any:
        """Anlagennutzungsgrad der Wärmerückgewinnung [1.1.5.7]."""
        return self._parameter_by_slug("heat_recovery_annual_eff")

    @property
    def volume_flow_full_load_hours(self) -> Any:
        """Jährliche Volumenstrom-Volllaststunden [1.1.5.8]."""
        return self._parameter_by_slug("volume_flow_full_load_hours")

    @property
    def pSFP(self) -> Any:
        """Spezifische Ventilatorleistung [pSFP]."""
        return self._parameter_by_slug("pSFP")

    @property
    def pV(self) -> Any:
        """Elektrische Leistung der Lüftung [pV]."""
        return self._parameter_by_slug("pV")

    @property
    def tV_e(self) -> Any:
        """Jährliche Volllaststunden der Lüftung [tV,e]."""
        return self._parameter_by_slug("tV_e")

    @property
    def EV(self) -> Any:
        """Jährlicher Elektrizitätsbedarf der Lüftung [EV]."""
        return self._parameter_by_slug("EV")

    @property
    def row_146(self) -> Any:
        """row-146 [row-146]."""
        return self._parameter_by_slug("row_146")

    @property
    def Fe(self) -> Any:
        """Externe Wärmeeintragsleistung [1.1.6.1]."""
        return self._parameter_by_slug("Fe")

    @property
    def Fi(self) -> Any:
        """Interne Wärmeeintragsleistung [1.1.6.2]."""
        return self._parameter_by_slug("Fi")

    @property
    def Qi(self) -> Any:
        """Interne Wärmeeinträge pro Tag [1.1.6.3]."""
        return self._parameter_by_slug("Qi")

    @property
    def cooling_required(self) -> Any:
        """Notwendigkeit einer Kühlung [1.1.6.4]."""
        return self._parameter_by_slug("cooling_required")

    @property
    def berechnet(self) -> Any:
        """berechnet! [berechnet]."""
        return self._parameter_by_slug("berechnet")

    @property
    def notwendigkeit_einer_kuehlung_ohne_fensterlueftung(self) -> Any:
        """Notwendigkeit einer Kühlung (Ohne Fensterlüftung) [notwendigkeit-einer-k-hlung-ohne-fensterl-ftung]."""
        return self._parameter_by_slug("notwendigkeit_einer_kuehlung_ohne_fensterlueftung")

    @property
    def notwendigkeit_einer_kuehlung(self) -> Any:
        """Notwendigkeit einer Kühlung [1.1.6.4-2]."""
        return self._parameter_by_slug("notwendigkeit_einer_kuehlung")

    @property
    def notwendigkeit_einer_kuehlung_mit_unterstuetzender_fensterlueftung_bei_belegung(self) -> Any:
        """Notwendigkeit einer Kühlung (Mit unterstützender Fensterlüftung bei Belegung) [notwendigkeit-einer-k-hlung-mit-unterst-tzender-fensterl-ftung-bei-belegung]."""
        return self._parameter_by_slug("notwendigkeit_einer_kuehlung_mit_unterstuetzender_fensterlueftung_bei_belegung")

    @property
    def notwendigkeit_einer_kuehlung_ohne_fensterlueftung(self) -> Any:
        """Notwendigkeit einer Kühlung (Ohne Fensterlüftung) [notwendigkeit-einer-k-hlung-ohne-fensterl-ftung-2]."""
        return self._parameter_by_slug("notwendigkeit_einer_kuehlung_ohne_fensterlueftung")

    @property
    def FC(self) -> Any:
        """Klimakälteleistungsbedarf [1.1.6.5]."""
        return self._parameter_by_slug("FC")

    @property
    def FC(self) -> Any:
        """Klimakälteleistungsbedarf [1.1.6.5-2]."""
        return self._parameter_by_slug("FC")

    @property
    def FC(self) -> Any:
        """Klimakälteleistungsbedarf [1.1.6.5-3]."""
        return self._parameter_by_slug("FC")

    @property
    def tC(self) -> Any:
        """Jährliche Volllaststunden der Raumkühlung [1.1.6.6]."""
        return self._parameter_by_slug("tC")

    @property
    def QC(self) -> Any:
        """Jährlicher Klimakältebedarf [1.1.6.7]."""
        return self._parameter_by_slug("QC")

    @property
    def QC(self) -> Any:
        """Jährlicher Klimakältebedarf [1.1.6.7-2]."""
        return self._parameter_by_slug("QC")

    @property
    def row_162(self) -> Any:
        """row-162 [row-162]."""
        return self._parameter_by_slug("row_162")

    @property
    def vx(self) -> Any:
        """Feuchtequellen (exklusive Personen) [vx]."""
        return self._parameter_by_slug("vx")

    @property
    def hrec_j(self) -> Any:
        """Feuchtegehalt-Änderungsgrad der Lüftungsanlage [hrec,j]."""
        return self._parameter_by_slug("hrec_j")

    @property
    def vi_min(self) -> Any:
        """Minimale Feuchte der Raumluft [vi,min]."""
        return self._parameter_by_slug("vi_min")

    @property
    def ve_min(self) -> Any:
        """Minimale Feuchte der Aussenluft [ve,min]."""
        return self._parameter_by_slug("ve_min")

    @property
    def rL(self) -> Any:
        """Dichte der Raumluft [rL]."""
        return self._parameter_by_slug("rL")

    @property
    def vHu(self) -> Any:
        """Feuchtebedarf [vHu]."""
        return self._parameter_by_slug("vHu")

    @property
    def pHu(self) -> Any:
        """Spez. Wärmeleistungsbedarf für Befeuchtung [pHu]."""
        return self._parameter_by_slug("pHu")

    @property
    def tHu(self) -> Any:
        """Jährliche Volllaststunden [tHu]."""
        return self._parameter_by_slug("tHu")

    @property
    def Qhu(self) -> Any:
        """Jährlicher spez. Wärmebedarf für Befeuchtung [Qhu]."""
        return self._parameter_by_slug("Qhu")

    @property
    def row_172(self) -> Any:
        """row-172 [row-172]."""
        return self._parameter_by_slug("row_172")

    @property
    def HT(self) -> Any:
        """Transmissions-Wärmetransferkoeffizient [1.1.7.1]."""
        return self._parameter_by_slug("HT")

    @property
    def HV(self) -> Any:
        """Lüftungs-Wärmetransferkoeffizient [1.1.7.2]."""
        return self._parameter_by_slug("HV")

    @property
    def heating_design_temp(self) -> Any:
        """Wärmetransferkoeffizient [1.1.7.3]."""
        return self._parameter_by_slug("heating_design_temp")

    @property
    def t(self) -> Any:
        """Zeitkonstante [1.1.7.4]."""
        return self._parameter_by_slug("t")

    @property
    def qcor(self) -> Any:
        """Temperaturkorrektur [1.1.7.5]."""
        return self._parameter_by_slug("qcor")

    @property
    def FT_i(self) -> Any:
        """Norm-Transmissionswärmeverlust [FT,i]."""
        return self._parameter_by_slug("FT_i")

    @property
    def n_min(self) -> Any:
        """Thermisch wirksame Mindest-Luftwechselrate [n,min]."""
        return self._parameter_by_slug("n_min")

    @property
    def qv_min_i(self) -> Any:
        """Thermisch wirksamer Mindest-Luftvolumenstrom [qv,min,i]."""
        return self._parameter_by_slug("qv_min_i")

    @property
    def FV_i(self) -> Any:
        """Norm-Lüftungswärmeverlust [FV,i]."""
        return self._parameter_by_slug("FV_i")

    @property
    def FHL(self) -> Any:
        """Norm-Heizlast [1.1.7.6]."""
        return self._parameter_by_slug("FHL")

    @property
    def tH(self) -> Any:
        """Jährliche Volllaststunden der Raumheizung [1.1.7.7]."""
        return self._parameter_by_slug("tH")

    @property
    def QH_li0(self) -> Any:
        """Heizwärmebedarf Basiswert SIA 380/1 [QH,li0]."""
        return self._parameter_by_slug("QH_li0")

    @property
    def DQH_li(self) -> Any:
        """Steigungsfaktor Grenzwert Heizwärmebedarf SIA 380/1 [DQH,li]."""
        return self._parameter_by_slug("DQH_li")

    @property
    def V_AE(self) -> Any:
        """Standard-Aussenluft-Volumenstrom SIA 380/1 [V/AE]."""
        return self._parameter_by_slug("V_AE")

    @property
    def qth(self) -> Any:
        """Thermisch wirksamer Aussenluft-Volumenstrom [1.1.7.8]."""
        return self._parameter_by_slug("qth")

    @property
    def QH_eff(self) -> Any:
        """Jährlicher Heizwärmebedarf [1.1.7.9]."""
        return self._parameter_by_slug("QH_eff")

    @property
    def row_189(self) -> Any:
        """row-189 [row-189]."""
        return self._parameter_by_slug("row_189")

    @property
    def reference_unit(self) -> Any:
        """Bezugseinheit [1.1.8.1]."""
        return self._parameter_by_slug("reference_unit")

    @property
    def domestic_hot_water_per_unit(self) -> Any:
        """Nutzwarmwasserbedarf pro Bezugseinheit [1.1.8.2]."""
        return self._parameter_by_slug("domestic_hot_water_per_unit")

    @property
    def units_per_person(self) -> Any:
        """Anzahl Bezugseinheiten pro Person [1.1.8.3]."""
        return self._parameter_by_slug("units_per_person")

    @property
    def domestic_hot_water_per_person(self) -> Any:
        """Warmwasserbedarf pro Person [1.1.8.4]."""
        return self._parameter_by_slug("domestic_hot_water_per_person")

    @property
    def water_to_hot_water_ratio(self) -> Any:
        """Verhältnis Wasserbedarf zu Warmwasserbedarf [1.1.8.5]."""
        return self._parameter_by_slug("water_to_hot_water_ratio")

    @property
    def water_per_person(self) -> Any:
        """Wasserbedarf pro Person [1.1.8.6]."""
        return self._parameter_by_slug("water_per_person")

    @property
    def QW(self) -> Any:
        """Jährlicher Wärmebedarf für Warmwasser [1.1.8.7]."""
        return self._parameter_by_slug("QW")
