# -*- coding: utf-8 -*-
"""Generate src/energytools/raumdaten/_generated.py from the dataset package.

The generated module contains two mixins with **static ``@property``
accessors** — one per room use and one per parameter — so that IDEs and
type checkers offer full autocompletion and hover docs when the user types
``ds.room_uses.`` or ``profile.``.

Regenerate after a dataset change:

    pixi run -e dev python tools/generate_accessors.py
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from energytools.raumdaten._slugs import (  # noqa: E402
    PARAMETER_ALIASES,
    ROOM_USE_SLUGS,
    parameter_slug,
    slugify_label,
)

REPO = Path(__file__).resolve().parents[1]
PACKAGE = REPO / "data" / "datasets" / "V221" / "package.json"
OUT = REPO / "src" / "energytools" / "raumdaten" / "_generated.py"

# Attribute names that must never be shadowed by generated accessors.
RESERVED = {
    "value", "values", "parameters", "room_use", "release_id", "as_dict",
    "to_frame", "parameter_catalog", "standard", "zielwert", "bestand",
    "unit", "validate", "from_dict",
}


def _doc_clean(text: str) -> str:
    return (text or "").replace('"""', "'").replace("\\", "/")


def main() -> None:
    pkg = json.loads(PACKAGE.read_text(encoding="utf-8"))
    room_uses = pkg["room_uses"]
    parameters = pkg["parameters"]

    lines: list[str] = []
    lines.append('"""AUTO-GENERATED by tools/generate_accessors.py — do not edit.')
    lines.append("")
    lines.append("Static ``@property`` accessors for the Raumdaten dataset (V221).")
    lines.append("Regenerate with: pixi run -e dev python tools/generate_accessors.py")
    lines.append('"""')
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from typing import Any")
    lines.append("")
    lines.append("")
    lines.append("class RoomUseProperties:")
    lines.append('    """Generated ``@property`` accessors for the 45 standard room uses."""')
    lines.append("")
    for ru in room_uses:
        code = ru["code"]
        slug = ROOM_USE_SLUGS.get(code)
        if not slug:
            continue
        name_de = _doc_clean(ru["name"]["de"])
        lines.append("    @property")
        lines.append(f'    def {slug}(self) -> Any:')
        lines.append(f'        """{code} {name_de}."""')
        lines.append(f'        return self._room_use_by_slug("{slug}")')
        lines.append("")
    lines.append("")
    lines.append("")
    lines.append("class ParameterProperties:")
    lines.append('    """Generated ``@property`` accessors for the parameter catalog."""')
    lines.append("")
    used_slugs: set[str] = set()

    def reserve(slug: str, label_de: str) -> str | None:
        """Reserve a property name; on collision fall back to the label slug,
        then to a numbered suffix — a duplicate would silently shadow the
        first parameter (e.g. symbol ``hR`` of Raumhöhe vs Raumwirkungsgrad).
        """
        if slug in used_slugs:
            label_slug = slugify_label(label_de)
            if label_slug and label_slug not in used_slugs:
                slug = label_slug
            else:
                counter = 2
                while f"{slug}_{counter}" in used_slugs:
                    counter += 1
                slug = f"{slug}_{counter}"
        used_slugs.add(slug)
        return slug

    for p in parameters:
        pid = p["id"]
        if pid in ("Symbol",):
            continue
        label_de = _doc_clean(p.get("label", {}).get("de", ""))
        slug = parameter_slug(pid, p.get("symbol", ""), label_de)
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", slug) or slug in RESERVED:
            continue
        slug = reserve(slug, label_de)
        lines.append("    @property")
        lines.append(f"    def {slug}(self) -> Any:")
        doc = label_de or p.get("symbol") or pid
        lines.append(f'        """{doc} [{pid}]."""')
        lines.append(f'        return self._parameter_by_slug("{slug}")')
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(room_uses)} room-use + {len(parameters)} parameter accessors)")


if __name__ == "__main__":
    main()
